# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' soft threshold function
#'
#' @param L input matrix
#' @param lambda threshold parameter  
#' @return thresholded matrix L
soft_full <- function(L, lambda) {
    .Call(`_LinearDetect_soft_full`, L, lambda)
}

lm_break_fit_block <- function(data_y, data_x, lambda, lambda2, max_iteration, tol, initial_phi, blocks, cv_index) {
    .Call(`_LinearDetect_lm_break_fit_block`, data_y, data_x, lambda, lambda2, max_iteration, tol, initial_phi, blocks, cv_index)
}

lm_break_fit_block_new <- function(data_y, data_x, lambda, lambda2, max_iteration, tol, initial_phi, blocks, cv_index) {
    .Call(`_LinearDetect_lm_break_fit_block_new`, data_y, data_x, lambda, lambda2, max_iteration, tol, initial_phi, blocks, cv_index)
}

ggm_break_fit_block <- function(data_y, data_x, lambda, lambda2, max_iteration, tol, initial_phi, blocks, cv_index) {
    .Call(`_LinearDetect_ggm_break_fit_block`, data_y, data_x, lambda, lambda2, max_iteration, tol, initial_phi, blocks, cv_index)
}

lm_partial_break_fit_block <- function(data_y, data_x, lambda, lambda2, max_iteration, tol, initial_phi, initial_phi_2, blocks, cv_index, fixed_index, nonfixed_index) {
    .Call(`_LinearDetect_lm_partial_break_fit_block`, data_y, data_x, lambda, lambda2, max_iteration, tol, initial_phi, initial_phi_2, blocks, cv_index, fixed_index, nonfixed_index)
}

var_break_fit_block <- function(data, lambda, lambda2, q, max_iteration, tol, initial_phi, blocks, cv_index) {
    .Call(`_LinearDetect_var_break_fit_block`, data, lambda, lambda2, q, max_iteration, tol, initial_phi, blocks, cv_index)
}

#' lambda warm up for linear regression model
#'
#' @param data_y input matrix Y
#' @param data_x input matrix X 
#' @param blocks the vector of blocks 
#' @param cv_index the vector of indices for validation
#' @return a value for parameter lambda
lambda_warm_up_lm <- function(data_y, data_x, blocks, cv_index) {
    .Call(`_LinearDetect_lambda_warm_up_lm`, data_y, data_x, blocks, cv_index)
}

lambda_warm_up_var <- function(data, q, blocks, cv_index) {
    .Call(`_LinearDetect_lambda_warm_up_var`, data, q, blocks, cv_index)
}

